### ISSUE TITLE
Discrepancy between quotas and input limits

### ISSUE THREAD

**Issue by juanitosvq** [awsdocs/amazon-transcribe-developer-guide#10]
Hi, we've noticed that the values for maximum audio length and file size are different in these two pages:
https://docs.aws.amazon.com/transcribe/latest/dg/input.html 
> Less than 4 hours in length or less than 2 Gb of audio data

https://docs.aws.amazon.com/transcribe/latest/dg/limits-guidelines.html#limits
> Maximum audio file length | 7,200 seconds
> Maximum audio file size | 1 GB

We tested transcribe and it seems to support up to 4 hours of content, but the most recent change was in the limits page to reduce the values to 2 hours/1GB:
https://github.com/awsdocs/amazon-transcribe-developer-guide/commit/c8d37e17f0e2a8b677e34a29192c34d59dacd540#diff-164ff7ae972b6b4b29add63728a73540

I was hoping someone could shed some light on this.
Thanks!
Juan

**Comment by jongogogo** [comment]
Same thing with the 
> Maximum size of a vocabulary filter | 5 MB

It should be 50kB

**Comment by parsash2** [comment]
Hi all!

juanitosvq, I really appreciate you taking the time to provide feedback. The documentation on both pages is now consistent. I'll be continuing to update the page to make things more clear.

jongogogo, according to what I can find internally, the maximum size of the vocabulary filter should be 50 kB. Were you able to create a vocabulary filter that has a value of 5 MB?
