### ISSUE TITLE
FailureReasons do not cover the case of too small files

### ISSUE THREAD

**Issue by baxtree** [awsdocs/amazon-transcribe-developer-guide#12]
Hi, 

Got the following failure reason when transcribing audio less than 500 milliseconds:

> The input media file length is too small. Check the length of the file and try your request again.

Can you please update the doc on that? Thanks!

**Comment by baxtree** [comment]
The section talked about can be found in here:
https://docs.aws.amazon.com/transcribe/latest/dg/API_TranscriptionJob.html#transcribe-Type-TranscriptionJob-FailureReason

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
