### ISSUE TITLE
documentation for PHP?

### ISSUE THREAD

**Issue by lucenarenato** [awsdocs/amazon-transcribe-developer-guide#13]
I'm a PHP developer, I would like to use transcribe real time transcriptions, but I haven't found documentation for PHP about this tool, do you have a strength? For audio translation, I found it, but I didn't find real time.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
