### ISSUE TITLE
Unexpected Web Socket Frame Received

### ISSUE THREAD

**Issue by vchelur** [awsdocs/amazon-transcribe-developer-guide#14]
After connecting to the transcribe web socket server, I am faced with the following error when I send an audio data frame:

b'\x00\x00\x00\xa3\x00\x00\x00ah\x10k\xe1\x0f:exception-type\x07\x00\x13BadRequestException\r:content-type\x07\x00\x10application/json\r:message-type\x07\x00\texception{"Message":"Unexpected WebSocket frame received."}\xbd\xceK\x8a'

I followed the event stream encoding, so I'm not sure what's going on here

Thanks!

**Comment by parsash2** [comment]
Hi there!

Could you provide me with the code you're using to run the request. I can share it with the team to see if we can find your issue.

**Comment by marioDatatris** [comment]
> Hi there!
> 
> Could you provide me with the code you're using to run the request. I can share it with the team to see if we can find your issue.

I had the same problem. AWS support do not anwser.
 You could follow this example: https://stackoverflow.com/questions/57875522/bad-request-exception-when-trying-to-use-aws-transcribe-using-python-to-transc

**Comment by marioDatatris** [comment]
> After connecting to the transcribe web socket server, I am faced with the following error when I send an audio data frame:
> 
> b'\x00\x00\x00\xa3\x00\x00\x00ah\x10k\xe1\x0f:exception-type\x07\x00\x13BadRequestException\r:content-type\x07\x00\x10application/json\r:message-type\x07\x00\texception{"Message":"Unexpected WebSocket frame received."}\xbd\xceK\x8a'
> 
> I followed the event stream encoding, so I'm not sure what's going on here
> 
> Thanks!

I am sure you did not create de stream audio evente correctly.
See this sdk https://github.com/awslabs/amazon-transcribe-streaming-sdk to learn how to do it. 
"stream.input_stream.send_audio_event(audio_chunk=chunk)" create all the necessary from the audio_chunk

If you are using java:
https://github.com/aws/aws-sdk-js-v3/blob/master/packages/eventstream-marshaller/src/EventStreamMarshaller.ts

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
