### ISSUE TITLE
SRT and VTT files start with 0?

### ISSUE THREAD

**Issue by cjmorrison** [awsdocs/amazon-transcribe-developer-guide#18]
I am very new to AWS so my apologies if this is already a thing. Can there be an option to start at caption files at an index of 1?

I noticed the files start with an index of 0, However I do not think that is standard and it seems to break things. Including  other aws codes like [amazon-translate-video-subtitles-captions-translation](https://github.com/aws-samples/amazon-translate-video-subtitles-captions-translation)

The closest thing to authority on the subjects also suggest these typically start at 1. I suspect that many tools expect this format which is why things are breaking.

https://www.w3.org/TR/webvtt1/#introduction-metadata
https://www.matroska.org/technical/subtitles.html#srt-subtitle

![2021_12_06_17_54_33_Window](https://user-images.githubusercontent.com/3035488/144936040-d6fcef30-ee16-4370-9207-565b009144d7.png)
s

**Comment by lisdelan** [comment]
Hi there, we've added a new parameter (OutputStartIndex) that allows you to specify 0 or 1. You can see some examples of this here: https://docs.aws.amazon.com/transcribe/latest/dg/subtitles.html#subtitles-how-to.
